#!/usr/bin/env python3
"""Fuse text-stream and behavior-stream item candidates.

This is a CPU-only post-processing script. It reads candidate JSONL files
generated by evaluate_candidates.py, aligns samples by row_index/sample_id, and
evaluates union, min-rank, and RRF item-level fusion. The primary fused JSONL is
kept compatible with rerank.py by writing candidate_item_ids/candidate_details.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


NOT_AVAILABLE = "not_available"
INF_RANK = 10**12


@dataclass
class Candidate:
    item_id: str
    rank: int
    detail: dict[str, Any] = field(default_factory=dict)


@dataclass
class CandidateSample:
    sample_id: str
    row_index: int | None
    target_item_id: str
    history_item_id: list[str]
    candidates: list[Candidate]
    raw: dict[str, Any] = field(default_factory=dict)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fuse two SID candidate streams at item level.")
    parser.add_argument("--text-candidates", type=Path, required=True)
    parser.add_argument("--behavior-candidates", type=Path, required=True)
    parser.add_argument("--test-csv", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--ks", type=int, nargs="+", default=[1, 3, 5, 10, 20, 50])
    parser.add_argument("--lambda-text", type=float, default=0.5)
    parser.add_argument("--k-rrf", type=float, default=60.0)
    parser.add_argument("--text-name", default="text")
    parser.add_argument("--behavior-name", default="behavior")
    parser.add_argument("--dedup-by-item", default="true", choices=["true", "false"])
    parser.add_argument("--schema-sample-size", type=int, default=3)
    return parser.parse_args()


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with open(path, "r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write("\n")


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})


def rate(numerator: int | float, denominator: int | float) -> float:
    return 0.0 if denominator == 0 else float(numerator) / float(denominator)


def item_sort_key(value: Any) -> tuple[int, int | str]:
    text = str(value)
    try:
        return (0, int(text))
    except ValueError:
        return (1, text)


def rank_of(target_item_id: str, candidates: list[str]) -> int | None:
    target = str(target_item_id)
    for rank, item_id in enumerate(candidates):
        if str(item_id) == target:
            return rank
    return None


def rank_metrics(ranks: list[int | None], ks: list[int]) -> dict[str, Any]:
    out: dict[str, Any] = {"num_samples": len(ranks)}
    for k in ks:
        hits = 0
        ndcg_sum = 0.0
        for rank in ranks:
            if rank is not None and rank < k:
                hits += 1
                ndcg_sum += 1.0 / math.log2(rank + 2)
        out[f"hr@{k}"] = rate(hits, len(ranks))
        out[f"ndcg@{k}"] = rate(ndcg_sum, len(ranks))
    return out


def choose_field(record: dict[str, Any], candidates: list[str]) -> str | None:
    for field_name in candidates:
        if field_name in record and record.get(field_name) not in (None, ""):
            return field_name
    return None


def normalize_sample_id(value: Any, fallback_idx: int) -> str:
    if value is None or value == "":
        return str(fallback_idx)
    return str(value)


def parse_row_index(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def test_targets(test_csv: Path) -> dict[str, str]:
    rows = read_csv_rows(test_csv)
    targets: dict[str, str] = {}
    for idx, row in enumerate(rows):
        targets[str(idx)] = str(row.get("item_id", "")).strip()
    return targets


def schema_preview(path: Path, sample_size: int) -> dict[str, Any]:
    rows = read_jsonl(path)[: max(sample_size, 0)]
    preview = []
    for row in rows:
        details = row.get("candidate_details", [])
        first_detail = details[0] if isinstance(details, list) and details else {}
        preview.append(
            {
                "keys": sorted(row.keys()),
                "candidate_details_keys": sorted(first_detail.keys()) if isinstance(first_detail, dict) else [],
                "candidate_item_ids_len": len(row.get("candidate_item_ids", []))
                if isinstance(row.get("candidate_item_ids"), list)
                else NOT_AVAILABLE,
            }
        )
    return {"path": path.as_posix(), "num_preview_rows": len(preview), "preview": preview}


def detail_index(record: dict[str, Any]) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    details = record.get("candidate_details", [])
    if not isinstance(details, list):
        return out
    for detail in details:
        if not isinstance(detail, dict):
            continue
        item_id = str(detail.get("item_id", ""))
        if item_id and item_id not in out:
            out[item_id] = detail
    return out


def normalize_nested_record(
    record: dict[str, Any],
    fallback_idx: int,
    targets: dict[str, str],
    field_mapping: dict[str, str],
    dedup_by_item: bool,
) -> CandidateSample:
    sample_field = choose_field(record, ["row_index", "sample_id"])
    sample_id = normalize_sample_id(record.get(sample_field) if sample_field else None, fallback_idx)
    row_index = parse_row_index(record.get("row_index", sample_id))
    target_field = choose_field(record, ["target_item_id", "label_item_id"])
    target_item_id = str(record.get(target_field, "")).strip() if target_field else ""
    if not target_item_id:
        target_item_id = targets.get(sample_id, "")
    history = [str(item_id) for item_id in record.get("history_item_id", [])] if isinstance(record.get("history_item_id"), list) else []

    field_mapping.setdefault("sample_id", sample_field or "file_order")
    field_mapping.setdefault("target_item_id", target_field or "test_csv_by_sample_id")
    field_mapping.setdefault("candidate_items", "candidate_item_ids")
    field_mapping.setdefault("rank", "list_order_1_based")

    details_by_item = detail_index(record)
    candidates: list[Candidate] = []
    seen: set[str] = set()
    raw_items = record.get("candidate_item_ids", [])
    if not isinstance(raw_items, list):
        raw_items = []
    for idx, item_id_raw in enumerate(raw_items, start=1):
        item_id = str(item_id_raw)
        if dedup_by_item and item_id in seen:
            continue
        seen.add(item_id)
        candidates.append(Candidate(item_id=item_id, rank=idx, detail=details_by_item.get(item_id, {})))
    return CandidateSample(
        sample_id=sample_id,
        row_index=row_index,
        target_item_id=target_item_id,
        history_item_id=history,
        candidates=candidates,
        raw=record,
    )


def normalize_flat_records(
    rows: list[dict[str, Any]],
    targets: dict[str, str],
    field_mapping: dict[str, str],
    dedup_by_item: bool,
) -> dict[str, CandidateSample]:
    grouped: dict[str, list[tuple[int, dict[str, Any]]]] = {}
    for idx, record in enumerate(rows):
        sample_field = choose_field(record, ["row_index", "sample_id"])
        sample_id = normalize_sample_id(record.get(sample_field) if sample_field else None, idx)
        grouped.setdefault(sample_id, []).append((idx, record))
        field_mapping.setdefault("sample_id", sample_field or "file_order")

    out: dict[str, CandidateSample] = {}
    for sample_id, pairs in grouped.items():
        first = pairs[0][1]
        target_field = choose_field(first, ["target_item_id", "label_item_id"])
        target_item_id = str(first.get(target_field, "")).strip() if target_field else targets.get(sample_id, "")
        candidate_field = choose_field(first, ["pred_item_id", "candidate_item_id"])
        if candidate_field is None and "item_id" in first and "target_item_id" in first:
            candidate_field = "item_id"
        if candidate_field is None:
            raise ValueError(
                "Cannot identify flat candidate item field. Expected pred_item_id/candidate_item_id "
                "or item_id with target_item_id present."
            )
        rank_field = choose_field(first, ["rank", "candidate_rank", "candidate_rank_1_based", "rank_1_based"])
        rank0_field = choose_field(first, ["rank_0_based", "candidate_rank_0_based"])
        field_mapping.setdefault("target_item_id", target_field or "test_csv_by_sample_id")
        field_mapping.setdefault("candidate_items", candidate_field)
        field_mapping.setdefault("rank", rank_field or rank0_field or "sample_order_1_based")

        candidates: list[Candidate] = []
        seen: set[str] = set()
        for order, (_, record) in enumerate(pairs, start=1):
            item_id = str(record.get(candidate_field, ""))
            if not item_id:
                continue
            if dedup_by_item and item_id in seen:
                continue
            seen.add(item_id)
            if rank_field:
                try:
                    rank = int(float(record.get(rank_field)))
                except (TypeError, ValueError):
                    rank = order
            elif rank0_field:
                try:
                    rank = int(float(record.get(rank0_field))) + 1
                except (TypeError, ValueError):
                    rank = order
            else:
                rank = order
            candidates.append(Candidate(item_id=item_id, rank=max(rank, 1), detail=dict(record)))
        out[sample_id] = CandidateSample(
            sample_id=sample_id,
            row_index=parse_row_index(first.get("row_index", sample_id)),
            target_item_id=target_item_id,
            history_item_id=[],
            candidates=sorted(candidates, key=lambda c: (c.rank, item_sort_key(c.item_id))),
            raw=first,
        )
    return out


def load_candidate_samples(
    path: Path,
    targets: dict[str, str],
    dedup_by_item: bool,
) -> tuple[dict[str, CandidateSample], dict[str, Any]]:
    rows = read_jsonl(path)
    field_mapping: dict[str, str] = {}
    nested = bool(rows and isinstance(rows[0].get("candidate_item_ids"), list))
    if nested:
        samples = {
            normalize_sample_id(row.get("row_index", row.get("sample_id")), idx): normalize_nested_record(
                row,
                idx,
                targets,
                field_mapping,
                dedup_by_item,
            )
            for idx, row in enumerate(rows)
        }
        mode = "nested_candidate_item_ids"
    else:
        samples = normalize_flat_records(rows, targets, field_mapping, dedup_by_item)
        mode = "flat_candidate_rows"
    schema = {
        "path": path.as_posix(),
        "num_rows": len(rows),
        "mode": mode,
        "field_mapping": field_mapping,
    }
    return samples, schema


def rank_map(sample: CandidateSample | None) -> dict[str, Candidate]:
    if sample is None:
        return {}
    out: dict[str, Candidate] = {}
    for candidate in sorted(sample.candidates, key=lambda c: (c.rank, item_sort_key(c.item_id))):
        if candidate.item_id not in out:
            out[candidate.item_id] = candidate
    return out


def top_items(sample: CandidateSample | None, k: int) -> set[str]:
    if sample is None:
        return set()
    ordered = sorted(sample.candidates, key=lambda c: (c.rank, item_sort_key(c.item_id)))
    return {candidate.item_id for candidate in ordered[:k]}


def best_source_type(text_detail: dict[str, Any] | None, behavior_detail: dict[str, Any] | None) -> tuple[str, int | None, float]:
    details = [detail for detail in [text_detail, behavior_detail] if detail]
    best_type = "exact"
    best_level: int | None = None
    best_bucket = 1.0
    priority = {"exact": 3, "prefix@4": 2, "prefix@3": 2, "prefix@2": 1, "prefix@1": 1}
    best_priority = -1
    for detail in details:
        source_type = str(detail.get("source_type", ""))
        expansion_level_raw = detail.get("expansion_level")
        try:
            expansion_level = int(expansion_level_raw)
        except (TypeError, ValueError):
            expansion_level = None
        current_priority = priority.get(source_type, 0)
        if current_priority > best_priority:
            best_priority = current_priority
            best_type = source_type or "exact"
            best_level = expansion_level
        try:
            bucket = float(detail.get("bucket_size", best_bucket))
            best_bucket = min(best_bucket, bucket) if best_bucket > 1 else bucket
        except (TypeError, ValueError):
            pass
    return best_type, best_level, best_bucket


def make_fused_candidates(
    text_sample: CandidateSample | None,
    behavior_sample: CandidateSample | None,
    lambda_text: float,
    k_rrf: float,
    method: str,
) -> list[dict[str, Any]]:
    text_map = rank_map(text_sample)
    behavior_map = rank_map(behavior_sample)
    all_items = sorted(set(text_map) | set(behavior_map), key=item_sort_key)
    fused: list[dict[str, Any]] = []
    for item_id in all_items:
        text_candidate = text_map.get(item_id)
        behavior_candidate = behavior_map.get(item_id)
        text_rank = text_candidate.rank if text_candidate else None
        behavior_rank = behavior_candidate.rank if behavior_candidate else None
        min_rank = min(text_rank or INF_RANK, behavior_rank or INF_RANK)
        both = text_candidate is not None and behavior_candidate is not None
        rrf_score = 0.0
        if text_rank is not None:
            rrf_score += lambda_text / (k_rrf + text_rank)
        if behavior_rank is not None:
            rrf_score += (1.0 - lambda_text) / (k_rrf + behavior_rank)
        source_type, expansion_level, bucket_size = best_source_type(
            text_candidate.detail if text_candidate else None,
            behavior_candidate.detail if behavior_candidate else None,
        )
        row = {
            "item_id": item_id,
            "text_rank": text_rank,
            "behavior_rank": behavior_rank,
            "from_text": text_candidate is not None,
            "from_behavior": behavior_candidate is not None,
            "both_streams": both,
            "min_rank": min_rank,
            "rrf_score": rrf_score,
            "source_type": source_type,
            "expansion_level": expansion_level,
            "bucket_size": bucket_size,
        }
        fused.append(row)
    if method == "min_rank":
        fused.sort(
            key=lambda item: (
                item["min_rank"],
                0 if item["both_streams"] else 1,
                item["text_rank"] if item["text_rank"] is not None else INF_RANK,
                item["behavior_rank"] if item["behavior_rank"] is not None else INF_RANK,
                item_sort_key(item["item_id"]),
            )
        )
    elif method == "rrf":
        fused.sort(
            key=lambda item: (
                -item["rrf_score"],
                item["min_rank"],
                0 if item["both_streams"] else 1,
                item_sort_key(item["item_id"]),
            )
        )
    else:
        raise ValueError(f"Unsupported fusion method: {method}")
    for idx, item in enumerate(fused, start=1):
        item["rank"] = idx
        item["fusion_score"] = item["rrf_score"] if method == "rrf" else 1.0 / item["min_rank"]
        item["fusion_method"] = method
    return fused


def sample_target(text_sample: CandidateSample | None, behavior_sample: CandidateSample | None, targets: dict[str, str], sample_id: str) -> str:
    for sample in [text_sample, behavior_sample]:
        if sample and sample.target_item_id:
            return sample.target_item_id
    return targets.get(sample_id, "")


def sample_history(text_sample: CandidateSample | None, behavior_sample: CandidateSample | None) -> list[str]:
    for sample in [text_sample, behavior_sample]:
        if sample and sample.history_item_id:
            return sample.history_item_id
    return []


def evaluate_union(
    sample_ids: list[str],
    text_samples: dict[str, CandidateSample],
    behavior_samples: dict[str, CandidateSample],
    targets: dict[str, str],
    ks: list[int],
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    counts: dict[str, dict[int, int]] = {
        key: {k: 0 for k in ks}
        for key in [
            "text_hit",
            "behavior_hit",
            "union_hit",
            "text_only_hit",
            "behavior_only_hit",
            "both_hit",
            "neither_hit",
        ]
    }
    rows: list[dict[str, Any]] = []
    for sample_id in sample_ids:
        text_sample = text_samples.get(sample_id)
        behavior_sample = behavior_samples.get(sample_id)
        target_item_id = sample_target(text_sample, behavior_sample, targets, sample_id)
        row: dict[str, Any] = {"sample_id": sample_id, "target_item_id": target_item_id}
        for k in ks:
            text_hit = target_item_id in top_items(text_sample, k)
            behavior_hit = target_item_id in top_items(behavior_sample, k)
            union_hit = text_hit or behavior_hit
            text_only_hit = text_hit and not behavior_hit
            behavior_only_hit = behavior_hit and not text_hit
            both_hit = text_hit and behavior_hit
            neither_hit = not union_hit
            values = {
                "text_hit": text_hit,
                "behavior_hit": behavior_hit,
                "union_hit": union_hit,
                "text_only_hit": text_only_hit,
                "behavior_only_hit": behavior_only_hit,
                "both_hit": both_hit,
                "neither_hit": neither_hit,
            }
            for key, value in values.items():
                counts[key][k] += int(value)
                row[f"{key}@{k}"] = int(value)
        rows.append(row)
    metrics: dict[str, Any] = {"num_samples": len(sample_ids)}
    for key, by_k in counts.items():
        for k, count in by_k.items():
            metrics[f"{key}@{k}"] = rate(count, len(sample_ids))
            metrics[f"{key}_count@{k}"] = count
    for k in ks:
        metrics[f"union_gain_over_text@{k}"] = metrics[f"union_hit@{k}"] - metrics[f"text_hit@{k}"]
    return metrics, rows


def fusion_metrics(
    sample_ids: list[str],
    text_samples: dict[str, CandidateSample],
    behavior_samples: dict[str, CandidateSample],
    targets: dict[str, str],
    ks: list[int],
    lambda_text: float,
    k_rrf: float,
    method: str,
) -> tuple[dict[str, Any], dict[str, list[dict[str, Any]]], list[int | None]]:
    ranks: list[int | None] = []
    fused_by_sample: dict[str, list[dict[str, Any]]] = {}
    for sample_id in sample_ids:
        text_sample = text_samples.get(sample_id)
        behavior_sample = behavior_samples.get(sample_id)
        target_item_id = sample_target(text_sample, behavior_sample, targets, sample_id)
        fused = make_fused_candidates(text_sample, behavior_sample, lambda_text, k_rrf, method)
        fused_by_sample[sample_id] = fused
        ranks.append(rank_of(target_item_id, [item["item_id"] for item in fused]))
    return rank_metrics(ranks, ks), fused_by_sample, ranks


def metrics_rows(report: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for section in ["union_recall", "text_stream", "behavior_stream", "min_rank_fusion", "rrf_fusion"]:
        value = report.get(section)
        if not isinstance(value, dict):
            continue
        for metric, metric_value in value.items():
            if metric == "num_samples":
                continue
            rows.append({"section": section, "metric": metric, "value": metric_value})
    return rows


def stream_metrics(samples: dict[str, CandidateSample], sample_ids: list[str], targets: dict[str, str], ks: list[int]) -> dict[str, Any]:
    ranks: list[int | None] = []
    candidate_counts: list[int] = []
    for sample_id in sample_ids:
        sample = samples.get(sample_id)
        target_item_id = sample_target(sample, None, targets, sample_id)
        ordered = sorted(sample.candidates, key=lambda c: (c.rank, item_sort_key(c.item_id))) if sample else []
        ranks.append(rank_of(target_item_id, [candidate.item_id for candidate in ordered]))
        candidate_counts.append(len(ordered))
    metrics = rank_metrics(ranks, ks)
    metrics["candidate_count_mean"] = sum(candidate_counts) / len(candidate_counts) if candidate_counts else 0.0
    metrics["candidate_count_max"] = max(candidate_counts) if candidate_counts else 0
    return metrics


def rerank_detail(item: dict[str, Any]) -> dict[str, Any]:
    source_types: list[str] = []
    if item["from_text"]:
        source_types.append("text")
    if item["from_behavior"]:
        source_types.append("behavior")
    return {
        "item_id": item["item_id"],
        "source_type": item["source_type"],
        "source_sid": "",
        "matched_prefix": "",
        "sid_rank_0_based": max(int(item["min_rank"]) - 1, 0) if item["min_rank"] < INF_RANK else 999999,
        "expansion_level": item["expansion_level"],
        "bucket_size": item["bucket_size"],
        "all_source_types": source_types,
        "dual_source_types": source_types,
        "text_rank": "" if item["text_rank"] is None else item["text_rank"],
        "behavior_rank": "" if item["behavior_rank"] is None else item["behavior_rank"],
        "fusion_score": item["fusion_score"],
        "fusion_method": item["fusion_method"],
        "from_text": item["from_text"],
        "from_behavior": item["from_behavior"],
    }


def write_fused_outputs(
    out_dir: Path,
    sample_ids: list[str],
    text_samples: dict[str, CandidateSample],
    behavior_samples: dict[str, CandidateSample],
    targets: dict[str, str],
    fused_by_sample: dict[str, list[dict[str, Any]]],
    union_rows: list[dict[str, Any]],
) -> None:
    fused_jsonl = out_dir / "dual_fused_candidates.jsonl"
    flat_jsonl = out_dir / "dual_fused_candidates_flat.jsonl"
    per_sample_csv = out_dir / "per_sample_dual_fusion.csv"
    out_dir.mkdir(parents=True, exist_ok=True)
    with open(fused_jsonl, "w", encoding="utf-8") as nested_f, open(flat_jsonl, "w", encoding="utf-8") as flat_f:
        for sample_id in sample_ids:
            text_sample = text_samples.get(sample_id)
            behavior_sample = behavior_samples.get(sample_id)
            target_item_id = sample_target(text_sample, behavior_sample, targets, sample_id)
            row_index = text_sample.row_index if text_sample and text_sample.row_index is not None else None
            if row_index is None and behavior_sample is not None:
                row_index = behavior_sample.row_index
            history = sample_history(text_sample, behavior_sample)
            fused = fused_by_sample.get(sample_id, [])
            candidate_item_ids = [item["item_id"] for item in fused]
            candidate_details = [rerank_detail(item) for item in fused]
            record = {
                "row_index": row_index if row_index is not None else sample_id,
                "sample_id": sample_id,
                "target_item_id": target_item_id,
                "history_item_id": history,
                "candidate_item_ids": candidate_item_ids,
                "candidate_details": candidate_details,
                "candidates": fused,
                "candidate_hit_rank_0_based": rank_of(target_item_id, candidate_item_ids),
                "fusion_method": "rrf",
            }
            nested_f.write(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n")
            for item in fused:
                flat = {
                    "sample_id": sample_id,
                    "row_index": row_index if row_index is not None else sample_id,
                    "target_item_id": target_item_id,
                    "candidate_item_id": item["item_id"],
                    "rank": item["rank"],
                    "fusion_score": item["fusion_score"],
                    "fusion_method": item["fusion_method"],
                    "text_rank": "" if item["text_rank"] is None else item["text_rank"],
                    "behavior_rank": "" if item["behavior_rank"] is None else item["behavior_rank"],
                    "from_text": item["from_text"],
                    "from_behavior": item["from_behavior"],
                }
                flat_f.write(json.dumps(flat, ensure_ascii=False, sort_keys=True) + "\n")
    write_csv(
        per_sample_csv,
        sorted({key for row in union_rows for key in row.keys()}),
        union_rows,
    )


def write_markdown_report(out_dir: Path, report: dict[str, Any]) -> None:
    lines = [
        "# Dual-SID CF K512 Fusion Report",
        "",
        "## What Was Run",
        "",
        "This report fuses a text SID candidate stream and a behavior SID candidate stream at item level.",
        "No SFT/evaluate/rerank main logic is modified by this script.",
        "",
        "## Inputs",
        "",
        f"- Text candidates: `{report['inputs']['text_candidates']}`",
        f"- Behavior candidates: `{report['inputs']['behavior_candidates']}`",
        f"- Test CSV: `{report['inputs']['test_csv']}`",
        "",
        "## Key Diagnostics",
        "",
    ]
    union = report["union_recall"]
    rrf = report["rrf_fusion"]
    min_rank = report["min_rank_fusion"]
    text = report["text_stream"]
    behavior = report["behavior_stream"]
    for key in [
        "behavior_only_hit_count@20",
        "union_gain_over_text@20",
        "union_gain_over_text@50",
    ]:
        if key in union:
            lines.append(f"- {key}: `{union[key]}`")
    lines.extend(
        [
            "",
            "## Metrics",
            "",
            "| Section | HR@20 | NDCG@20 | HR@50 | NDCG@50 |",
            "|---|---:|---:|---:|---:|",
            f"| Text stream | {text.get('hr@20', 0):.6f} | {text.get('ndcg@20', 0):.6f} | {text.get('hr@50', 0):.6f} | {text.get('ndcg@50', 0):.6f} |",
            f"| Behavior stream | {behavior.get('hr@20', 0):.6f} | {behavior.get('ndcg@20', 0):.6f} | {behavior.get('hr@50', 0):.6f} | {behavior.get('ndcg@50', 0):.6f} |",
            f"| Union recall | {union.get('union_hit@20', 0):.6f} | n/a | {union.get('union_hit@50', 0):.6f} | n/a |",
            f"| Min-rank fusion | {min_rank.get('hr@20', 0):.6f} | {min_rank.get('ndcg@20', 0):.6f} | {min_rank.get('hr@50', 0):.6f} | {min_rank.get('ndcg@50', 0):.6f} |",
            f"| RRF fusion | {rrf.get('hr@20', 0):.6f} | {rrf.get('ndcg@20', 0):.6f} | {rrf.get('hr@50', 0):.6f} | {rrf.get('ndcg@50', 0):.6f} |",
            "",
            "## Interpretation Checklist",
            "",
            f"- `behavior_only_hit@20` exists: `{union.get('behavior_only_hit_count@20', 0) > 0}`",
            f"- `union_hit@20 > text_hit@20`: `{union.get('union_gain_over_text@20', 0) > 0}`",
            f"- `union_hit@50 > text_hit@50`: `{union.get('union_gain_over_text@50', 0) > 0}`",
            f"- `RRF HR@20 > text HR@20`: `{rrf.get('hr@20', 0) > text.get('hr@20', 0)}`",
            "",
            "If fusion does not improve the text stream, inspect candidate overlap, behavior-only hit counts, behavior stream candidate quality, and whether prefix expansion introduces too much noise.",
            "",
        ]
    )
    path = out_dir / "report.md"
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> None:
    args = parse_args()
    ks = sorted(set(k for k in args.ks if k > 0))
    dedup_by_item = args.dedup_by_item.lower() == "true"
    targets = test_targets(args.test_csv)
    text_samples, text_schema = load_candidate_samples(args.text_candidates, targets, dedup_by_item)
    behavior_samples, behavior_schema = load_candidate_samples(args.behavior_candidates, targets, dedup_by_item)
    sample_ids = sorted(set(text_samples) | set(behavior_samples), key=item_sort_key)
    if not sample_ids:
        raise ValueError("No aligned candidate samples found.")

    union_metrics, union_rows = evaluate_union(sample_ids, text_samples, behavior_samples, targets, ks)
    min_rank_metrics, _, _ = fusion_metrics(
        sample_ids,
        text_samples,
        behavior_samples,
        targets,
        ks,
        args.lambda_text,
        args.k_rrf,
        "min_rank",
    )
    rrf_metrics, rrf_by_sample, _ = fusion_metrics(
        sample_ids,
        text_samples,
        behavior_samples,
        targets,
        ks,
        args.lambda_text,
        args.k_rrf,
        "rrf",
    )
    text_metrics = stream_metrics(text_samples, sample_ids, targets, ks)
    behavior_metrics = stream_metrics(behavior_samples, sample_ids, targets, ks)

    schema_report = {
        "text": {**text_schema, "preview": schema_preview(args.text_candidates, args.schema_sample_size)},
        "behavior": {**behavior_schema, "preview": schema_preview(args.behavior_candidates, args.schema_sample_size)},
        "dedup_by_item": dedup_by_item,
        "sample_alignment": {
            "text_samples": len(text_samples),
            "behavior_samples": len(behavior_samples),
            "union_samples": len(sample_ids),
            "text_only_samples": len(set(text_samples) - set(behavior_samples)),
            "behavior_only_samples": len(set(behavior_samples) - set(text_samples)),
        },
    }
    report = {
        "inputs": {
            "text_candidates": args.text_candidates.as_posix(),
            "behavior_candidates": args.behavior_candidates.as_posix(),
            "test_csv": args.test_csv.as_posix(),
            "text_name": args.text_name,
            "behavior_name": args.behavior_name,
        },
        "outputs": {
            "dual_fused_candidates_jsonl": (args.out_dir / "dual_fused_candidates.jsonl").as_posix(),
            "dual_fused_candidates_flat_jsonl": (args.out_dir / "dual_fused_candidates_flat.jsonl").as_posix(),
            "dual_fusion_metrics_csv": (args.out_dir / "dual_fusion_metrics.csv").as_posix(),
            "per_sample_dual_fusion_csv": (args.out_dir / "per_sample_dual_fusion.csv").as_posix(),
            "schema_report_json": (args.out_dir / "schema_report.json").as_posix(),
            "report_md": (args.out_dir / "report.md").as_posix(),
        },
        "topk": ks,
        "rrf": {
            "lambda_text": args.lambda_text,
            "k_rrf": args.k_rrf,
            "rank_is_1_based": True,
        },
        "schema": schema_report,
        "text_stream": text_metrics,
        "behavior_stream": behavior_metrics,
        "union_recall": union_metrics,
        "min_rank_fusion": min_rank_metrics,
        "rrf_fusion": rrf_metrics,
        "notes": {
            "leakage_policy": "target item is used only for metrics; fusion uses only candidate item ids and ranks",
            "primary_fused_jsonl": "dual_fused_candidates.jsonl is written in a rerank.py-compatible nested format",
        },
    }

    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_fused_outputs(args.out_dir, sample_ids, text_samples, behavior_samples, targets, rrf_by_sample, union_rows)
    write_json(args.out_dir / "dual_fusion_report.json", report)
    write_json(args.out_dir / "schema_report.json", schema_report)
    write_csv(args.out_dir / "dual_fusion_metrics.csv", ["section", "metric", "value"], metrics_rows(report))
    write_markdown_report(args.out_dir, report)

    print(f"Wrote fused candidates: {args.out_dir / 'dual_fused_candidates.jsonl'}")
    print(f"Wrote fusion report: {args.out_dir / 'dual_fusion_report.json'}")
    print(f"Wrote schema report: {args.out_dir / 'schema_report.json'}")
    print(
        "Dual fusion summary: "
        f"text_HR@20={text_metrics.get('hr@20', NOT_AVAILABLE)} "
        f"behavior_HR@20={behavior_metrics.get('hr@20', NOT_AVAILABLE)} "
        f"union_HR@20={union_metrics.get('union_hit@20', NOT_AVAILABLE)} "
        f"minrank_HR@20={min_rank_metrics.get('hr@20', NOT_AVAILABLE)} "
        f"rrf_HR@20={rrf_metrics.get('hr@20', NOT_AVAILABLE)}"
    )


if __name__ == "__main__":
    main()
